### ISSUE TITLE
ppt-imgコマンドでのエラー

### ISSUE THREAD

**Issue by shinriyo** [akameco/popute-random-img#2]
原因は調べてませんが、サイト内の場所が変わったせいかエラーが発生します。
```
Error: Protocol "data:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:131:11)
    at Object.request (http.js:38:10)
    at get (/usr/local/lib/node_modules/popute-random-img/node_modules/got/index.js:33:18)
    at requestAsEventEmitter (/usr/local/lib/node_modules/popute-random-img/node_modules/got/index.js:85:2)
    at Promise (/usr/local/lib/node_modules/popute-random-img/node_modules/got/index.js:91:14)
    at new Promise (<anonymous>)
    at asPromise (/usr/local/lib/node_modules/popute-random-img/node_modules/got/index.js:90:9)
    at got (/usr/local/lib/node_modules/popute-random-img/node_modules/got/index.js:302:10)
    at popute.then.then.then.url (/usr/local/lib/node_modules/popute-random-img/index.js:17:4)
    at <anonymous>
(node:72777) UnhandledPromiseRejectionWarning: TypeError: Image required
    at module.exports (/usr/local/lib/node_modules/popute-random-img/node_modules/term-img/index.js:24:9)
    at poputeRandomImg.then.img (/usr/local/lib/node_modules/popute-random-img/cli.js:7:2)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:72777) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:72777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by akameco** [comment]
@shinriyo 報告ありがとうございます！
どうやらDataURLに変わっていたようです。修正しました

**Comment by shinriyo** [comment]
@akameco 今日知ったので実はまだ使えたことがなかったです。修正ありがとうございます。最新版で確認できました。
